# (really just for install target)

include ../../makefile.inc

all:

.PHONY: install
install:
	cp mount_external_media.sh $(MPBOX_INSTALL_DIR)/mpservice/bin
	chmod 755 $(MPBOX_INSTALL_DIR)/mpservice/bin/mount_external_media.sh

clean_all:

clean:
