#!/bin/sh

IFCONFIG=/sbin/ifconfig
GREP=/bin/grep
[ -e /bin/awk ] && AWK=/bin/awk
[ -e /usr/bin/awk ] && AWK=/usr/bin/awk
HOSTNAME=/bin/hostname
ROUTE=/sbin/route

ETH0_IPV4INFO=`${IFCONFIG} eth0 |${GREP} 'inet addr'`
ETH0_IPV4ADDRESS=`echo "${ETH0_IPV4INFO}" | ${AWK} '{ print $2 }' \
                       |${AWK} -F: '{ print $2 }'`
ETH0_IPV4BROADCAST=`echo "${ETH0_IPV4INFO}" | ${AWK} '{ print $3 }' \
                         |${AWK} -F: '{ print $2 }'`
ETH0_IPV4NETMASK=`echo "${ETH0_IPV4INFO}" | ${AWK} '{ print $4 }' \
                       |${AWK} -F: '{ print $2 }'`
ETH0_GATEWAY=`${ROUTE} -n |${GREP} UG |${GREP} eth0 |${AWK} '{ print $2 }'`
PRIMARY_HOSTNAME=`${HOSTNAME}`

echo "Content-type: text/xml; charset=utf-8"
echo "Cache-Control: no-cache"
echo "pragma: no-cache"
echo
echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
echo
echo "<system>"
echo "  <param name=\"ip_address_eth0\" value=\"${ETH0_IPV4ADDRESS}\" />"
echo "  <param name=\"ip_broadcast_eth0\" value=\"${ETH0_IPV4BROADCAST}\" />"
echo "  <param name=\"ip_netmask_eth0\" value=\"${ETH0_IPV4NETMASK}\" />"
echo "  <param name=\"ip_gateway_eth0\" value=\"${ETH0_GATEWAY}\" />"
echo "  <param name=\"hostname\" value=\"${PRIMARY_HOSTNAME}\" />"
echo "</system>"
