#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
 	echo "Starting network..."
	/etc/init.d/network start
	;;
  stop)
	echo -n "Stopping network..."
	/etc/init.d/network stop	
	;;
  restart|reload)
	/etc/init.d/network restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

