#!/bin/sh

echo "Running the mpbox linuxrc"

echo "Loading IDE kernel modules"
modprobe ide-core
modprobe ide-generic probe_mask=0x01

echo "Loading Realtek 8168 (ethernet) module"
insmod /mpservice/modules/r8168.ko

#
# Mount proc and sysfs
#
echo "Mounting /proc"
/bin/mount -t proc proc /proc
echo "Mounting /sys"
/bin/mount -t sysfs sys /sys

# remount root ramdisk partition as read-write
echo "Remounting /"
/bin/mount / -o remount,rw

"Mounting /dev/shm, etc."
/bin/mkdir -p /dev/pts
/bin/mkdir -p /dev/shm
/bin/mount -a
/bin/hostname -F /etc/hostname

echo "Mounting /mpservice/librarydb as a tmpfs"
mount -t tmpfs -o size=6M tmpfs /mpservice/librarydb
chmod 777 /mpservice/librarydb

#first try to mount /dev/hda1 (primary-master PATA drive) if it doesn't
#exist, try /dev/sda1, /dev/sdb1 
echo "Trying to mount /disk1 on hda1"
mount -text2 /dev/hda1 /disk1
if [ ${?} == "0" ]; then
  echo "Mounted /disk1 on /dev/hda1"
else
  echo "Trying to mount /disk1 on sda1"
  sleep 2
  mount -text2 /dev/sda1 /disk1
  if [ ${?} == "0" ]; then
    echo "Mounted /disk1 on /dev/sda1"
  else
    echo "Trying to mount /disk1 on sdb1"
    sleep 1
    mount -text2 /dev/sdb1 /disk1
    if [ ${?} == "0" ]; then
      echo "Mounted /disk1 on /dev/sdb1"
    else
      echo "Problem: Couldn't mount /disk1 on /dev/hda1, /dev/sda1, or /dev/sdb1"
      sleep 1
    fi
  fi
fi



if [ ! -f /disk1/mpservice_configuration.xml ]; then
  echo "Couldn't find mpservice_configuration.xml, so creating one"
  cp /mpservice/misc/mpbox_default_configuration.xml /disk1/mpservice_configuration.xml
fi

echo "Creating mDNS configuration file"
echo "mpservice" > /etc/Services.txt
echo "_http._tcp" >> /etc/Services.txt
echo "80" >> /etc/Services.txt
echo "name=val1" >> /etc/Services.txt

# Setting up mixer volume
echo "Setting up Mixer volumes"
aumix -v 100
aumix -p 100
aumix -w 100
aumix -l 100

exec /sbin/init
