#!/bin/sh

TOP_DIR=`pwd`

cat > makefile.inc <<EOF
MPBOX_ROOT= ${TOP_DIR}
MPBOX_INCLUDE= \${MPBOX_ROOT}/include
MPBOX_INCLUDE_FLAGS= -I\${MPBOX_INCLUDE}
MPBOX_LIB= \${MPBOX_ROOT}/lib
MPBOX_LIB_FLAGS= -L\${MPBOX_LIB}

MPBOX_THIRDPARTY= \${MPBOX_ROOT}/../downloads/

MPBOX_INSTALL_DIR= \${ROOTDIR}/romfs

MPSERVICE_ROOT= ${TOP_DIR}/../mpservice
MPSERVICE_INCLUDE= \${MPSERVICE_ROOT}/include
MPSERVICE_LIB= \${MPSERVICE_ROOT}/lib

EOF


